package com.model;
/**
 * 附件实体类
 */

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * Accessory generated by hbm2java
 */
public class Accessory implements java.io.Serializable {

	private String id;// 编号
	private String fileName;// 文件名
	private String url;// 路径
	public Accessory(String id, String fileName, String url) {
		super();
		this.id = id;
		this.fileName = fileName;
		this.url = url;
	}
	public Accessory() {
		super();
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getFileName() {
		return fileName;
	}
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}

}
