package com.model;
/**
 * 客户实体类
 */
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private String id;// 编号
	private Users users;// 客户经理编号
	private String name;// 名称
	private String region;// 地区
	private String grade;// 客户等级
	private Integer satisficing;// 客户满意度1.2.3.4.5颗星，星级越高等级越高
	private Integer credit;// 客户信用度1.2.3.4.5颗星，星级越高信用度越高
	private String address;// 地址
	private String postcode;// 邮编
	private String tel;// 电话
	private String fax;// 传真
	private String url;// 网址
	private String license;// 营业执照注册号
	private String legalPerson;// 法人
	private Long registeredCapital;// 注册资金
	private Long annualSalesVolume;// 年营业额
	private String openingBank;// 开户银行
	private String bankAccount;// 银行账户
	private String landTax;// 地税号
	private String nationalTax;// 国税号
	private String loseDate;// 确认流失时间
	private Integer state;// 流失状态0.1.2 0是未处理 1是暂缓流失 2是已流失
	public Customer(String id, Users users, String name, String region, String grade, Integer satisficing,
			Integer credit, String address, String postcode, String tel, String fax, String url, String license,
			String legalPerson, Long registeredCapital, Long annualSalesVolume, String openingBank, String bankAccount,
			String landTax, String nationalTax, String loseDate, Integer state) {
		super();
		this.id = id;
		this.users = users;
		this.name = name;
		this.region = region;
		this.grade = grade;
		this.satisficing = satisficing;
		this.credit = credit;
		this.address = address;
		this.postcode = postcode;
		this.tel = tel;
		this.fax = fax;
		this.url = url;
		this.license = license;
		this.legalPerson = legalPerson;
		this.registeredCapital = registeredCapital;
		this.annualSalesVolume = annualSalesVolume;
		this.openingBank = openingBank;
		this.bankAccount = bankAccount;
		this.landTax = landTax;
		this.nationalTax = nationalTax;
		this.loseDate = loseDate;
		this.state = state;
	}
	public Customer() {
		super();
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public Users getUsers() {
		return users;
	}
	public void setUsers(Users users) {
		this.users = users;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getRegion() {
		return region;
	}
	public void setRegion(String region) {
		this.region = region;
	}
	public String getGrade() {
		return grade;
	}
	public void setGrade(String grade) {
		this.grade = grade;
	}
	public Integer getSatisficing() {
		return satisficing;
	}
	public void setSatisficing(Integer satisficing) {
		this.satisficing = satisficing;
	}
	public Integer getCredit() {
		return credit;
	}
	public void setCredit(Integer credit) {
		this.credit = credit;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getPostcode() {
		return postcode;
	}
	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}
	public String getTel() {
		return tel;
	}
	public void setTel(String tel) {
		this.tel = tel;
	}
	public String getFax() {
		return fax;
	}
	public void setFax(String fax) {
		this.fax = fax;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getLicense() {
		return license;
	}
	public void setLicense(String license) {
		this.license = license;
	}
	public String getLegalPerson() {
		return legalPerson;
	}
	public void setLegalPerson(String legalPerson) {
		this.legalPerson = legalPerson;
	}
	public Long getRegisteredCapital() {
		return registeredCapital;
	}
	public void setRegisteredCapital(Long registeredCapital) {
		this.registeredCapital = registeredCapital;
	}
	public Long getAnnualSalesVolume() {
		return annualSalesVolume;
	}
	public void setAnnualSalesVolume(Long annualSalesVolume) {
		this.annualSalesVolume = annualSalesVolume;
	}
	public String getOpeningBank() {
		return openingBank;
	}
	public void setOpeningBank(String openingBank) {
		this.openingBank = openingBank;
	}
	public String getBankAccount() {
		return bankAccount;
	}
	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}
	public String getLandTax() {
		return landTax;
	}
	public void setLandTax(String landTax) {
		this.landTax = landTax;
	}
	public String getNationalTax() {
		return nationalTax;
	}
	public void setNationalTax(String nationalTax) {
		this.nationalTax = nationalTax;
	}
	public String getLoseDate() {
		return loseDate;
	}
	public void setLoseDate(String loseDate) {
		this.loseDate = loseDate;
	}
	public Integer getState() {
		return state;
	}
	public void setState(Integer state) {
		this.state = state;
	}
	
	
}
