package com.model;
/**
 * 业务移交审核实体类
 */

/**
 * TransferAudit generated by hbm2java
 */
public class TransferAudit implements java.io.Serializable {

	private String id;// 编号
	private Customer customer;//客户
	private Users users;// 移交给
	private SalesLeads salesLeads;//销售机会
	private Service service;//服务
	private String type;//业务类型
	private Integer state;// 状态0.1.2.3 0是未移交 1是移交待审核 2是审核退回 3是已移交
	private String unpassedCause;// 审核未通过原因
	public TransferAudit(String id, Customer customer, Users users, SalesLeads salesLeads, Service service, String type,
			Integer state, String unpassedCause) {
		super();
		this.id = id;
		this.customer = customer;
		this.users = users;
		this.salesLeads = salesLeads;
		this.service = service;
		this.type = type;
		this.state = state;
		this.unpassedCause = unpassedCause;
	}
	public TransferAudit() {
		super();
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public Customer getCustomer() {
		return customer;
	}
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	public Users getUsers() {
		return users;
	}
	public void setUsers(Users users) {
		this.users = users;
	}
	public SalesLeads getSalesLeads() {
		return salesLeads;
	}
	public void setSalesLeads(SalesLeads salesLeads) {
		this.salesLeads = salesLeads;
	}
	public Service getService() {
		return service;
	}
	public void setService(Service service) {
		this.service = service;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public Integer getState() {
		return state;
	}
	public void setState(Integer state) {
		this.state = state;
	}
	public String getUnpassedCause() {
		return unpassedCause;
	}
	public void setUnpassedCause(String unpassedCause) {
		this.unpassedCause = unpassedCause;
	}

}
