package com.model;
/**
 * 客户交往记录实体类
 */
/**
 * ContactRecord generated by hbm2java
 */
public class ContactRecord implements java.io.Serializable {

	private String id;//编号
	private Customer customer;//客户
	private String contactDate;//时间
	private String loaction;//地点
	private String outline;//概要
	private String content;//详细信息
	private String remark;//备注

	public ContactRecord() {
	}

	public ContactRecord(String id) {
		this.id = id;
	}

	public ContactRecord(String id, Customer customer, String contactDate, String loaction, String outline,
			String content, String remark) {
		this.id = id;
		this.customer = customer;
		this.contactDate = contactDate;
		this.loaction = loaction;
		this.outline = outline;
		this.content = content;
		this.remark = remark;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getContactDate() {
		return this.contactDate;
	}

	public void setContactDate(String contactDate) {
		this.contactDate = contactDate;
	}

	public String getLoaction() {
		return this.loaction;
	}

	public void setLoaction(String loaction) {
		this.loaction = loaction;
	}

	public String getOutline() {
		return this.outline;
	}

	public void setOutline(String outline) {
		this.outline = outline;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
