package com.model;
/**
 * 订单实体类
 */
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private String id;// 编号
	private Customer customer;// 客户编号
	private BigDecimal amount;// 金额
	private String orderDate;// 日期
	private String address;// 送货地址
	private String tel;// 电话
	private Integer state;// 状态 0未回款 1已回款
	private List<OrdersDetail> ordersDetails = new ArrayList<OrdersDetail>();//订单明细
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public Customer getCustomer() {
		return customer;
	}
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	public BigDecimal getAmount() {
		return amount;
	}
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	public String getOrderDate() {
		return orderDate;
	}
	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getTel() {
		return tel;
	}
	public void setTel(String tel) {
		this.tel = tel;
	}
	public Integer getState() {
		return state;
	}
	public void setState(Integer state) {
		this.state = state;
	}
	public List<OrdersDetail> getOrdersDetails() {
		return ordersDetails;
	}
	public void setOrdersDetails(List<OrdersDetail> ordersDetails) {
		this.ordersDetails = ordersDetails;
	}
	public Orders(String id, Customer customer, BigDecimal amount, String orderDate, String address, String tel,
			Integer state, List<OrdersDetail> ordersDetails) {
		super();
		this.id = id;
		this.customer = customer;
		this.amount = amount;
		this.orderDate = orderDate;
		this.address = address;
		this.tel = tel;
		this.state = state;
		this.ordersDetails = ordersDetails;
	}
	public Orders() {
		super();
	}

}
