package com.model;
/**
 * 用户实体类
 */

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String id;// 编号
	private UsersRole usersRole;// 用户角色
	private String userName;// 用户名
	private String password;// 密码
	private String registerDate;// 注册时间
	private String name;// 姓名
	private String sex;// 性别
	private String tel;// 电话
	private String dept;// 部门
	private String job;// 职位
	private Integer state;// 状态
	public Users(String id, UsersRole usersRole, String userName, String password, String registerDate, String name,
			String sex, String tel, String dept, String job, Integer state) {
		super();
		this.id = id;
		this.usersRole = usersRole;
		this.userName = userName;
		this.password = password;
		this.registerDate = registerDate;
		this.name = name;
		this.sex = sex;
		this.tel = tel;
		this.dept = dept;
		this.job = job;
		this.state = state;
	}
	public Users() {
		super();
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public UsersRole getUsersRole() {
		return usersRole;
	}
	public void setUsersRole(UsersRole usersRole) {
		this.usersRole = usersRole;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getRegisterDate() {
		return registerDate;
	}
	public void setRegisterDate(String registerDate) {
		this.registerDate = registerDate;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	public String getTel() {
		return tel;
	}
	public void setTel(String tel) {
		this.tel = tel;
	}
	public String getDept() {
		return dept;
	}
	public void setDept(String dept) {
		this.dept = dept;
	}
	public String getJob() {
		return job;
	}
	public void setJob(String job) {
		this.job = job;
	}
	public Integer getState() {
		return state;
	}
	public void setState(Integer state) {
		this.state = state;
	}
	
}
