package com.model;
/**
 * 目标计划实体类
 */
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * TargetPlan generated by hbm2java
 */
public class TargetPlan implements java.io.Serializable {

	private String id;// 编号
	private String creater;// 创建人
	private String name;// 名称
	private String type;// 计划类型
	private String executeDate;// 计划执行时间
	private Long customerCountPlan;// 计划客户量
	private Long customerCountComplete;// 客户完成量
	private Integer customerProportionComplete;// 客户完成比例1-100
	private Double salePlan;// 计划销售额
	private Double saleComplete;// 销售额完成量
	private Integer saleProportionComplete;// 销售额完成比例1-100
	private Integer state;// 状态0是启用 1是停用
	public TargetPlan(String id, String creater, String name, String type, String executeDate, Long customerCountPlan,
			Long customerCountComplete, Integer customerProportionComplete, Double salePlan, Double saleComplete,
			Integer saleProportionComplete, Integer state) {
		super();
		this.id = id;
		this.creater = creater;
		this.name = name;
		this.type = type;
		this.executeDate = executeDate;
		this.customerCountPlan = customerCountPlan;
		this.customerCountComplete = customerCountComplete;
		this.customerProportionComplete = customerProportionComplete;
		this.salePlan = salePlan;
		this.saleComplete = saleComplete;
		this.saleProportionComplete = saleProportionComplete;
		this.state = state;
	}
	public TargetPlan() {
		super();
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getCreater() {
		return creater;
	}
	public void setCreater(String creater) {
		this.creater = creater;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getExecuteDate() {
		return executeDate;
	}
	public void setExecuteDate(String executeDate) {
		this.executeDate = executeDate;
	}
	public Long getCustomerCountPlan() {
		return customerCountPlan;
	}
	public void setCustomerCountPlan(Long customerCountPlan) {
		this.customerCountPlan = customerCountPlan;
	}
	public Long getCustomerCountComplete() {
		return customerCountComplete;
	}
	public void setCustomerCountComplete(Long customerCountComplete) {
		this.customerCountComplete = customerCountComplete;
	}
	public Integer getCustomerProportionComplete() {
		return customerProportionComplete;
	}
	public void setCustomerProportionComplete(Integer customerProportionComplete) {
		this.customerProportionComplete = customerProportionComplete;
	}
	public Double getSalePlan() {
		return salePlan;
	}
	public void setSalePlan(Double salePlan) {
		this.salePlan = salePlan;
	}
	public Double getSaleComplete() {
		return saleComplete;
	}
	public void setSaleComplete(Double saleComplete) {
		this.saleComplete = saleComplete;
	}
	public Integer getSaleProportionComplete() {
		return saleProportionComplete;
	}
	public void setSaleProportionComplete(Integer saleProportionComplete) {
		this.saleProportionComplete = saleProportionComplete;
	}
	public Integer getState() {
		return state;
	}
	public void setState(Integer state) {
		this.state = state;
	}

	
}
