package com.model;

/**
 * 销售机会实体类
 */
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * SalesLeads generated by hbm2java
 */
public class SalesLeads implements java.io.Serializable {

	private String id;// 编号
	private Users users;// 用户
	private String creater;// 创建人
	private String createDate;// 创建时间
	private String client;// 客户名
	private String linkman;// 联系人
	private String tel;// 联系电话
	private String source;// 机会来源
	private Integer successRate;// 成功率0-100
	private String outline;// 概要
	private String content;// 机会描述
	private String allotDate;// 分配时间
	private Integer state;// 状态 0是未分配 1是已分配未开发2开发中3已归档
	private List<DevelopmentPlan> developmentPlans = new ArrayList<DevelopmentPlan>();//开发计划
	public SalesLeads() {
		super();
	}
	public SalesLeads(String id, Users users, String creater, String createDate, String client, String linkman,
			String tel, String source, Integer successRate, String outline, String content, String allotDate,
			Integer state, List<DevelopmentPlan> developmentPlans) {
		super();
		this.id = id;
		this.users = users;
		this.creater = creater;
		this.createDate = createDate;
		this.client = client;
		this.linkman = linkman;
		this.tel = tel;
		this.source = source;
		this.successRate = successRate;
		this.outline = outline;
		this.content = content;
		this.allotDate = allotDate;
		this.state = state;
		this.developmentPlans = developmentPlans;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public Users getUsers() {
		return users;
	}
	public void setUsers(Users users) {
		this.users = users;
	}
	public String getCreater() {
		return creater;
	}
	public void setCreater(String creater) {
		this.creater = creater;
	}
	public String getCreateDate() {
		return createDate;
	}
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}
	public String getClient() {
		return client;
	}
	public void setClient(String client) {
		this.client = client;
	}
	public String getLinkman() {
		return linkman;
	}
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}
	public String getTel() {
		return tel;
	}
	public void setTel(String tel) {
		this.tel = tel;
	}
	public String getSource() {
		return source;
	}
	public void setSource(String source) {
		this.source = source;
	}
	public Integer getSuccessRate() {
		return successRate;
	}
	public void setSuccessRate(Integer successRate) {
		this.successRate = successRate;
	}
	public String getOutline() {
		return outline;
	}
	public void setOutline(String outline) {
		this.outline = outline;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getAllotDate() {
		return allotDate;
	}
	public void setAllotDate(String allotDate) {
		this.allotDate = allotDate;
	}
	public Integer getState() {
		return state;
	}
	public void setState(Integer state) {
		this.state = state;
	}
	public List<DevelopmentPlan> getDevelopmentPlans() {
		return developmentPlans;
	}
	public void setDevelopmentPlans(List<DevelopmentPlan> developmentPlans) {
		this.developmentPlans = developmentPlans;
	}
	
}
