package com.model;
/**
 * 角色实体类
 */

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * UsersRole generated by hbm2java
 */
public class UsersRole implements java.io.Serializable {

	private String id;// 编号
	private String name;// 角色名称
	private Integer state;// 状态
	private String registerDate;// 注册时间
	private String describe;// 角色描述
	private List<Accredit> accredits = new ArrayList<Accredit>();//授权
	private List<Users> userses = new ArrayList<Users>();// 用户
	public UsersRole() {
		super();
	}
	public UsersRole(String id, String name, Integer state, String registerDate, String describe,
			List<Accredit> accredits, List<Users> userses) {
		super();
		this.id = id;
		this.name = name;
		this.state = state;
		this.registerDate = registerDate;
		this.describe = describe;
		this.accredits = accredits;
		this.userses = userses;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Integer getState() {
		return state;
	}
	public void setState(Integer state) {
		this.state = state;
	}
	public String getRegisterDate() {
		return registerDate;
	}
	public void setRegisterDate(String registerDate) {
		this.registerDate = registerDate;
	}
	public String getDescribe() {
		return describe;
	}
	public void setDescribe(String describe) {
		this.describe = describe;
	}
	public List<Accredit> getAccredits() {
		return accredits;
	}
	public void setAccredits(List<Accredit> accredits) {
		this.accredits = accredits;
	}
	public List<Users> getUserses() {
		return userses;
	}
	public void setUserses(List<Users> userses) {
		this.userses = userses;
	}

	
}
