package com.model;
/**
 * 授权实体类
 */

/**
 * Accredit generated by hbm2java
 */
public class Accredit implements java.io.Serializable {

	private String id;//编号
	private Limit limit;//权限
	private UsersRole usersRole;//角色

	public Accredit() {
	}

	public Accredit(String id) {
		this.id = id;
	}

	public Accredit(String id, Limit limit, UsersRole usersRole) {
		this.id = id;
		this.limit = limit;
		this.usersRole = usersRole;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Limit getLimit() {
		return this.limit;
	}

	public void setLimit(Limit limit) {
		this.limit = limit;
	}

	public UsersRole getUsersRole() {
		return this.usersRole;
	}

	public void setUsersRole(UsersRole usersRole) {
		this.usersRole = usersRole;
	}

}
